### ISSUE TITLE
we need ur help witth a poketmine project, we might get paid when we finish this project

### ISSUE THREAD

**Issue by matthew4444** [shoghicp/c-SURF#1]
we need ur help witth a poketmine project, we might get paid when we finish this project
https://github.com/UniversalMine/BigDrother  please look :)

**Comment by matthew4444** [comment]
I know a guy who owns 2 server companys, we can get paid for selling a completed version of the plugin? please help? so we can do it, I  don't want to project to die :(

**Comment by ara2am** [comment]
I think so too. As for me @shoghicp if you have started the project (pm) that you must finish it.

**Comment by matthew4444** [comment]
I'm trying

**Comment by matthew4444** [comment]
nice ssite though ;)
